version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: payment_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: databreach
      MYSQL_DATABASE: payment_gateway
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: payment_redis
    restart: no
    ports:
      - "6379:6379"

  payment-app:
    platform: linux/amd64
    build: .
    container_name: payment_gateway_app
    restart: no
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_gateway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: databreach
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379